### ISSUE TITLE
Code doesn't work anymore due to wasm changes?

### ISSUE THREAD

**Issue by jairoxyz** [drblgn/rabbit_wasm#2]
Hey there, your brilliant code stopped working, I guess due to changes in the web assembly. First error is thrown because the embed page doesn't return any cookies anymore. Disabling getCookie then produces the next error when trying to instantiate the web assembly: `[LinkError: WebAssembly.instantiate(): Import #71 module="wbg" function="__wbindgen_closure_wrapper101" error: function import requires a callable]` So, obviously some additional functions have been added. New wasm is now in `https://rabbitstream.net/images/loading.png?v=0.6`

Hope you can fix it :)

Thanks!

**Comment by drblgn** [comment]
> Hey there, your brilliant code stopped working, I guess due to changes in the web assembly. First error is thrown because the embed page doesn't return any cookies anymore. Disabling getCookie then produces the next error when trying to instantiate the web assembly: `[LinkError: WebAssembly.instantiate(): Import #71 module="wbg" function="__wbindgen_closure_wrapper101" error: function import requires a callable]` So, obviously some additional functions have been added. New wasm is now in `https://rabbitstream.net/images/loading.png?v=0.6`
> 
> Hope you can fix it :)
> 
> Thanks!

thanks man. working on it !

**Comment by jairoxyz** [comment]
Great, thanks a lot! I have tried my luck decompling it using WASM Toolkit but the pesudo code produced doesn't make much sense to me. I can see closure_wrapper101 is declared in the code but no function definition for it I can find. But then I have no clue about wasm :D What tool are you using to decompile?

Cheers,

Jx-

**Comment by drblgn** [comment]
should be fixed now can you try the updated version ?

> Great, thanks a lot! I have tried my luck decompling it using WASM Toolkit but the pesudo code produced doesn't make much sense to me. I can see closure_wrapper101 is declared in the code but no function definition for it I can find. But then I have no clue about wasm :D What tool are you using to decompile?
> 
> Cheers,
> 
> Jx-

I don't bother decompiling the wasm since the pseudo code is basically unreadable. I just check for what the wasm actually wants as the returned value from the functions it calls. I just use chrome or firefox devtools.

edit: oh btw the function definiton for closure_wrapper101 is in the min.js file not the wasm file!

**Comment by jiamid** [comment]
super cool, It can be used directly.
The new version add user-agent to the verification.

**Comment by jairoxyz** [comment]
Yo man, really excellent coding. Fixes work perfectly fine. I just fixed some typo in User-Agent and Referer in getMeta, not that it seems to matter lol. I have a fork of your api version here: https://github.com/jairoxyz/rabbit_wasm_api where I added some npm script tags and dockerfile, in case anyone wants to run in a container.
And thanks for the explanations. I now get it that most of those functions are actually still in the JS and the wasm just imports and calls them. 

Cheers,

Jx-

**Comment by jiamid** [comment]
me too!
https://github.com/jiamid/wasm_service

but my service just to gen keys
I used the cache to save meta and img.

**Comment by jairoxyz** [comment]
> edit: oh btw the function definiton for closure_wrapper101 is in the min.js file not the wasm file!

Yes, function definitions are in the JS. Just a question, it seem to work either way but the definitions I find are like this:

```
rV.wbg.__wbindgen_closure_wrapper95 = function (rJ, rK, rx) {
      return rT(rE(rJ, rK, 2, rg));
    };
    rV.wbg.__wbindgen_closure_wrapper97 = function (rJ, rK, rx) {
      return rT(rE(rJ, rK, 2, rW));
    };
    rV.wbg.__wbindgen_closure_wrapper99 = function (rJ, rK, rx) {
      return rT(rE(rJ, rK, 2, rN));
    };
    rV.wbg.__wbindgen_closure_wrapper101 = function (rJ, rK, rx) {
      return rT(rE(rJ, rK, 9, rN));
    };
```
So wrapper93 is gone and wrapper101 is defined as above. Again, not that it seems to matter :D

**Comment by drblgn** [comment]
seems to be working after the update
