### ISSUE TITLE
Help me to understand this

### ISSUE THREAD

**Issue by fsmdeveloper** [drblgn/rabbit_wasm#4]
bro, how can i get xrax value/embed id from rapidstream? I get sourch with tmdb/imdb id from vidsrc. but how can I get xrax id from rapidstream? please help me.

**Comment by jairoxyz** [comment]
rapidstream or rabbitstream? Do you have an example link?

**Comment by drblgn** [comment]
> bro, how can i get xrax value/embed id from rapidstream? I get sourch with tmdb/imdb id from vidsrc. but how can I get xrax id from rapidstream? please help me.

do you mean how to get the embed id from an embed link? 
then as an example: rabbitstream/v2/embed-4/(xrax)?z=

but if you mean how to get an embed id without the embed link then you need a scraper for whatever site you are using to get the content you want to scrape

**Comment by fsmdeveloper** [comment]
Sorry, brother! I mean RabbitStream. Is it like Vidsrc.to? I want to get the HLS URL from RabbitStream. Is it possible? I can get the HLS URL from Vidsrc using the TMDB ID. I want to get it like this. Is it possible?

**Comment by drblgn** [comment]
> [drblgn](https://github.com/drblgn) Sorry, brother! I mean RabbitStream. Is it like Vidsrc.to? I want to get the HLS URL from RabbitStream. Is it possible? I can get the HLS URL from Vidsrc using the TMDB ID. I want to get it like this. Is it possible?

hmmm. i don't think you can use the tmdb id since the xrax values change overtime. as i said you need to use a scraper to get the xrax values from a site that uses rabbitstream as host for it's videos.

**Comment by drblgn** [comment]
if you have questions please write to me on discord: drblgn
