### ISSUE TITLE
Patched yet again

### ISSUE THREAD

**Issue by doiraduc** [drblgn/rabbit_wasm#6]
Hey! Thank you for your hard work.
Unfortunately, some things have changed with the streaming sites that used Vidcloud and this doesn't work anymore.

Before, the embeds that the sites returned were rabbitstream.net if the site was using Vidcloud (e.g. sflix.to, flixhq.to, etc.) and megacloud.tv if the site was using Megacloud (e.g. sflix.is, 1flix.to, etc.)

First of all, the domains have changed, and the sites that used rabbitstream now return a mix of venusembed.site, grostembed.online and others (check and refresh multiple times to see: [sflix.to/ajax/episode/sources/5437060](https://sflix.to/ajax/episode/sources/5437060)). The sites that used Megacloud changed just the tld (megacloud.tube). The thing is, they seem to use the same player js so their source code might be shared, just the domain is different (also the xrax value is the same in all the embeds returned by the api).
Second, the embeds no longer return the meta tag necessary for the getMeta function to run. So this is an issue too.

**Comment by oOICEMANOo** [comment]
> Hey! Thank you for your hard work. Unfortunately, some things have changed with the streaming sites that used Vidcloud and this doesn't work anymore.
> 
> Before, the embeds that the sites returned were rabbitstream.net if the site was using Vidcloud (e.g. sflix.to, flixhq.to, etc.) and megacloud.tv if the site was using Megacloud (e.g. sflix.is, 1flix.to, etc.)
> 
> First of all, the domains have changed, and the sites that used rabbitstream now return a mix of venusembed.site, grostembed.online and others (check and refresh multiple times to see: [sflix.to/ajax/episode/sources/5437060](https://sflix.to/ajax/episode/sources/5437060)). The sites that used Megacloud changed just the tld (megacloud.tube). The thing is, they seem to use the same player js so their source code might be shared, just the domain is different (also the xrax value is the same in all the embeds returned by the api). Second, the embeds no longer return the meta tag necessary for the getMeta function to run. So this is an issue too.

I also just started digging into the latest changes to try and get something working, other than the rolling domain's it also looks like getMeta possibly needs updated from "fyq" to "j_crt". Then it seems like we're missing a few functions here's the errors I go and the code I added to get past the error (NOTE: Code added was a guess, I'm not sure if its correct or not)
[LinkError: WebAssembly.instantiate(): Import #7 module="wbg" function="__wbindgen_number_get" error: function import requires a callable] 
ADDED
'__wbindgen_number_get': function(offset, index) {
        let obj = get(index);
        if (typeof obj === 'number') {
          getArr32()[offset / 4] = 1;
          getArr32()[(offset / 4) + 1] = obj;
        } else {
          getArr32()[offset / 4] = 0;
        }
      },
 [LinkError: WebAssembly.instantiate(): Import #45 module="wbg" function="__wbg_localStorage_3d538af21ea07fcc" error: function import requires a callable]
ADDED
'__wbg_localStorage_3d538af21ea07fcc': function(index) {
        return addToStack(fake_window.localStorage);
      },
 [LinkError: WebAssembly.instantiate(): Import #50 module="wbg" function="__wbindgen_is_object" error: function import requires a callable]
ADDED
'__wbindgen_is_object': function(arg0) {
        let val = get(arg0);
        let ret = typeof val === 'object' && val !== null;
        return ret;
      },
[LinkError: WebAssembly.instantiate(): Import #51 module="wbg" function="__wbg_crypto_1d1f22824a6a080c" error: function import requires a callable]
ADDED
'__wbg_crypto_1d1f22824a6a080c': function(arg0) {
        const ret = get(arg0).crypto;
        return addToStack(ret);
      },
[LinkError: WebAssembly.instantiate(): Import #52 module="wbg" function="__wbg_process_4a72847cc503995b" error: function import requires a callable]

-- UNKNOWN --

**Comment by rzmic** [comment]
help anyone has resolved this? i really need it, temporary using puppeter so slow and unstable ;(

**Comment by jairoxyz** [comment]
@oOICEMANOo very helpful, thanks a lot. They also changed they greet() function to groot(). It's in the wasm exports but when I try to call it I get unreachable error. Will try to implement the remaining functions and see if the error goes away 
@rzmic can you share your puppeteer solution.  Would be great to use it while I try to solve wasm code.

Thanks.

**Comment by jiamid** [comment]
I have completed the environment as much as possible and have been able to obtain pid, kversion, kid, and ktime, but the keys cannot be found. I hope it will be helpful to you.
https://github.com/jiamid/wasm_service/blob/master/src/gap/rabbit_temp.ts

**Comment by jairoxyz** [comment]
@jiamid great progress, I see they are definitely calling window.navigate in function Y and that is what fails with fake_window. Maybe there is a wasm function declaration missing or incomplete?

**Comment by luismendoza-ec** [comment]
@jairoxyz any luck?

**Comment by jairoxyz** [comment]
Not yet. Was hoping @jiamid could make use of the stuff I debugger:)

**Comment by luismendoza-ec** [comment]
> Not yet. Was hoping @jiamid could make use of the stuff I debugger:)

Do they just changed the keys or do you think they have added another thing?

**Comment by jiamid** [comment]
1.The current issue is that PID may also be incorrect,Unable to use the current PID to obtain sources.
2.window.navigate()  should be after window.jwt_plugin(Q0),but the jwt_plugin is not fully operational.

**Comment by jairoxyz** [comment]
@jiamid yes, I noticed that sources are not retrieved with the KID, KVERSION and PID you get. I made a puppeteer solution that works more or less and noticed that the same happened when not using stealth mode and also when not sending referer header to getsources call. I tried the latter in your solution but no change. I think they make a stronger fingerprint with the wasm that cannot be made with the fake window object. I saw you import canvas but don't use it for anything - did you test with that?

**Comment by jiamid** [comment]
kversion and kid is same to my browser,but pid is only can use once，it is error。
I test canvas，but I am not very familiar with Canvas in JavaScript，
it will be used in
 __wbg_createElement_03cf347ddad1c8c0：create canvas element
 __wbg_getContext_dfc91ab0837db1d1：get canvas.getContext('2d')
 __wbg_drawImage_cb13768a1bdc04bd：context2d.drawImage(img,)  /images/image.png?v=0.1.0

**Comment by luismendoza-ec** [comment]
> @jiamid yes, I noticed that sources are not retrieved with the KID, KVERSION and PID you get. I made a puppeteer solution that works more or less and noticed that the same happened when not using stealth mode and also when not sending referer header to getsources call. I tried the latter in your solution but no change. I think they make a stronger fingerprint with the wasm that cannot be made with the fake window object. I saw you import canvas but don't use it for anything - did you test with that?

Can you please your implementation with Puppeteer? I was thinking in a temp solution using a real chrome browser instance and with websockets.

**Comment by jiamid** [comment]
But imageData seems to change frequently.

**Comment by jairoxyz** [comment]
@jiamid image data changes? You mean the image.png itself or image data array inside code? Maybe it's what I saw in the `Al` variable in the navigate method? Will debug again and copy values.

@luismendoza-ec I'm fixing some stuff to make it more stable before I put it in git. Will let you know.

Jx-

**Comment by luismendoza-ec** [comment]
> @jiamid image data changes? You mean the image.png itself or image data array inside code? Maybe it's what I saw in the `Al` variable in the navigate method? Will debug again and copy values.
> 
> @luismendoza-ec I'm fixing some stuff to make it more stable before I put it in git. Will let you know.
> 
> Jx-

I saw the images resources vary depending the "version" they request, so probably they have added some kind of tiny variation for the same file but in different versions.

Thanks!

**Comment by luismendoza-ec** [comment]
I have a key that we can try for test, anyone is close just waiting to find the key?

**Comment by luismendoza-ec** [comment]
![image](https://github.com/user-attachments/assets/6cdd0c3a-a8b8-4a1b-879f-2368d51ba5dc)
I did with emulation, not optimized yet, but giving me 2 secs in a regular server, in my local computer about 4 secs with a poor connection.

**Comment by fsmdeveloper** [comment]
> ![image](https://private-user-images.githubusercontent.com/125885777/379522308-6cdd0c3a-a8b8-4a1b-879f-2368d51ba5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTc1OTMsIm5iZiI6MTcyOTc1NzI5MywicGF0aCI6Ii8xMjU4ODU3NzcvMzc5NTIyMzA4LTZjZGQwYzNhLWE4YjgtNGExYi04NzlmLTIzNjhkNTFiYTVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwODA4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDZiN2MxNTk5Mzk5ZGM1YzI4MGQ0MTlhMDhkYjAwM2VkOGMxZmYyMDhiZTMyYjJhNjhlNzFjNmFkZjE0ZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KzX1FJ822vXeoUWAI_T0-ARq907gQxEJFuCB2Kxk5wA) I did with emulation, not optimized yet, but giving me 2 secs in a regular server, in my local computer about 4 secs with a poor connection.

Bro, how? can you shared the fixed code, please?

**Comment by jairoxyz** [comment]
@jiamid @luismendoza-ec ping me here jairoxyz@mailfence.com if you like :)

**Comment by jairoxyz** [comment]
@jiamid Hi there, any luck with those jwt_plugin and navigate calls? I checked the array of what looks like pixel values passed to the navigate function and it's length is 108760, so either a bigger image or something else.

**Comment by jiamid** [comment]
I have new task to do.
maybe size in this
1.500*500
2.65*50

发自我的iPhone


------------------ Original ------------------
From: JairoX ***@***.***&gt;
Date: Sun,Oct 27,2024 8:36 PM
To: jiamid ***@***.***&gt;
Subject: Re: [drblgn/rabbit_wasm] Patched yet again (Issue #6)





 
@jiamid Hi there, any luck with those jwt_plugin and navigate calls? I checked the array of what looks like pixel values passed to the navigate function and it's length is 108760, so either a bigger image or something else.

**Comment by luismendoza-ec** [comment]
Hello guys, thanks everyone for all the effort.

@jairoxyz what is beign send to jwt_plugin is the wasm file, internally the jwt_plugin is executing its functions and populating the required data.

@jairoxyz @jiamid We should make a group somewhere and discuss there, just in case someone related with this implementation is looking for this.

**Comment by jairoxyz** [comment]
> 1.500*500

108760 divided by 4 (R, G, B, Alpha) is 27,190 pixels, so size could be 190 x 143 but the values don't really look like pixels cause Alpha should be 255: [0,97,115,109,1,0,0,0,1,240,1,32,96,2,127,127.........], so not sure. Could also be the array is generated by wasm and then reduced to keys array by the navigate function.

**Comment by luismendoza-ec** [comment]
> > 1.500*500
> 
> Hi @jiamid ,
> 
> 108760 divided by 4 (R, G, B, Alpha) is 27,190 pixels, so size could be 190 x 143 but the values don't really look like pixels cause Alpha should be 255: [0,97,115,109,1,0,0,0,1,240,1,32,96,2,127,127.........], so not sure. Could also be the array is generated by wasm and then reduced to keys array by the navigate function. Is still think some of the wasm functions are not complete because navigate should be available after groot and jwt_plugin. And your pid is wrong, so maybe it's a good idea to use canvas and a real window object, either from npm jsdom or puppeteer-real-browser. Just a few ideas :)

I did that, using a "real" window is giving still a wrong pid and my idea is that is just regarding the fingerprint they are detecting host, referer, ua

**Comment by jairoxyz** [comment]
Well, we can't know what you mean by real window if you don't share any of your code. What we do know is that they use code from here https://github.com/drbh/wasm-fingerprint for generating a fingerprint by drawing an image into a canvas. HTTP headers can be easily set, so that is not the problem.

**Comment by luismendoza-ec** [comment]
> Well, we can't know what you mean by real window if you don't share any of your code. What we do know is that they use code from here https://github.com/drbh/wasm-fingerprint for generating a fingerprint by drawing an image into a canvas. HTTP headers can be easily set, so that is not the problem.

I mean using the real chrome browser to debug all the script and wasm operations more closer.

Btw good one for the wasm-fingerprint, I was thinking to connect to the real browser with websockets and just change the xrax and force the process to produce a new fingerprint, but seems like they have controlled that also, probably playing with it more I will get it.

**Comment by jairoxyz** [comment]
@jiamid I debugged the wbg function that generates the dataurl from the canvas and it is different from what we have. This could already be the issue.

**Comment by jiamid** [comment]
@jairoxyz Can you call jwt_plugin to generate the navige() function ?
I tested that image_data and dataURL are consistent for a certain period of time

**Comment by jairoxyz** [comment]
@jiamid no, wasn't able to get the navigate function. If the image data that is converted to data url changes with every call, it has to be generated inside the wasm by the canvas functions defined in the JS. There are several drawing functions that we haven't defined yet like fillRect and fillText. So maybe instead of the emojis they are now rendering something random made of text and shapes. Needs more debugging and all wbg functions need to be defined. I debugged wbg_getImageData and that returns the pixels of image.png, so that is OK.

**Comment by luismendoza-ec** [comment]
> @jiamid no, wasn't able to get the navigate function. If the image data that is converted to data url changes with every call, it has to be generated inside the wasm by the canvas functions defined in the JS. There are several drawing functions that we haven't defined yet like fillRect and fillText. So maybe instead of the emojis they are now rendering something random made of text and shapes. Needs more debugging and all wbg functions need to be defined. I debugged wbg_getImageData and that returns the pixels of image.png, so that is OK.

Can we work together on this?

**Comment by jiamid** [comment]
fillRect and fillText is not used
Very willing to cooperate

**Comment by luismendoza-ec** [comment]
> fillRect and fillText is not used Very willing to cooperate 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Luis Mendoza ***@***.***&gt; Date: Tue,Oct 29,2024 7:23 PM To: jiamid ***@***.***&gt; Subject: Re: [drblgn/rabbit_wasm] Patched yet again (Issue #6) @jiamid no, wasn't able to get the navigate function. If the image data that is converted to data url changes with every call, it has to be generated inside the wasm by the canvas functions defined in the JS. There are several drawing functions that we haven't defined yet like fillRect and fillText. So maybe instead of the emojis they are now rendering something random made of text and shapes. Needs more debugging and all wbg functions need to be defined. I debugged wbg_getImageData and that returns the pixels of image.png, so that is OK. Can we work together on this? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

how can I contact you, we need to work under same project, so we can collaborate better, and if we do debug sessions we can easily get this done.

**Comment by oOICEMANOo** [comment]
also willing to help out, I started digging into this a few weeks ago and got tied up into other things now circling back, looks like some progress is happening which is great to see!

**Comment by luismendoza-ec** [comment]
Hey friends! It’s been a few interesting days trying to solve this, and JSDom and other techniques to represent things even close to what I need have made everything quite complicated. The validation and generation of the fingerprint is complex and depends on many factors, so even a minor change can prevent it from generating correctly.

The best solution I could implement (after temporarily handling Puppeteer and pools to intercept the HLS) is the following:

1. A single Puppeteer instance that doesn’t demand much from the system serves as the perfect sandbox, allowing all validations and WebAssembly (WASM) operations to run smoothly.
2. Injection of modified code to control certain aspects, validations, and shape the data exactly as I need it.
3. The browser’s connection to a socket hub that allows me to control it on demand (not to be confused with a reload operation).

**What I’m practically doing is:**
- Loading the site just once, letting resources and validations take place, and preventing resources that might later block from being released.
- Making this sandbox communicate via sockets to handle my requests.
- From my script that I want to scrape, I send the media ID I need.
- The sandbox (without any HTTP requests) generates the necessary fingerprint (which I’ve modified in certain parts to make unique).
- The sandbox responds with the fingerprint and other parameters needed for the request.
- From my script’s side, I make the request for the sources, and with the data obtained, apply the logic of their obfuscation to decrypt it.
- On the script’s side, I sanitize the URL and get it ready for consumption.

**Requests:**
- The browser only makes one to load the sandbox (resources, WASM, etc.).
- The script makes one to fetch the unique data of each embed and another to get the source (a JSON with the encrypted source). After that, I have the HLS.

I’ve tested it with some embeds, and it’s going well, and the best part is that it works in headless mode.

I’m leaving a few images and signing off (I need to sleep).

**P.D.:** I’ll improve a few things when I return with recharged energy. I know I can make it even better, but as it stands, it works very well.

![image](https://github.com/user-attachments/assets/27e56c5c-748b-45be-953b-f73cff11bfef)
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/59db5d45-3801-4060-8519-cacaf3bfaf80">
![image](https://github.com/user-attachments/assets/303170de-d784-4b1b-8ab3-17248c0e4189)

**Comment by jairoxyz** [comment]
Hey @luismendoza-ec  interesting but quiet complex solution :) I know for sure someone solved it by instantiating the wasm correctly in node.js but he won't share it. But it means it is possible the same way as @drblgn did.

**Comment by luismendoza-ec** [comment]
> Hey @luismendoza-ec interesting but quiet complex solution :) I know for sure someone solved it by instantiating the wasm correctly in node.js but he won't share it. But it means it is possible the same way as @drblgn did.

My friend Jairo, it's likely that yes, at some point someone will achieve it. It's not an easy task, and they will have invested many hours, probably days, and they won't release it either.

My solution isn't complex; I have it well assembled, and it works well in multitasking. Honestly, I feel satisfied because it can handle thousands of executions without trouble.

But I tried to be practical; I barely use Puppeteer for the sandbox. Going further than that by trying to hook every call of the wasm and trying to guess through the many conditions they have to solve it without the sandbox would be investing more time into something that they're going to change at some point.

Imagine, being practical and efficient is solving this in such a way that it takes you less time than they take to release the next version, or your work will have been for nothing :)

**Comment by jairoxyz** [comment]
> fillRect and fillText is not used Very willing to cooperate

Hi @jiamid, I debugged rect, fillRect and fillText and they are all called. It draws 3 rects into the canvas and the same emojis at coordinate 50, 70: ❤️🤪🎉👋

**Comment by jiamid** [comment]
I try remove they，it can run success

**Comment by jiamid** [comment]
I think we should adopt the @luismendoza-ec  method and achieve a good result through optimization. He's right, if we spend more time than they spend updating versions, it's meaningless.

**Comment by jairoxyz** [comment]
Yes, I would definitely like to try it but @luismendoza-ec would have to share his solution first. A private GIT maybe?

**Comment by jairoxyz** [comment]
As I thought, @luismendoza-ec  doesn't want to share anything ....

**Comment by luismendoza-ec** [comment]
> As I thought, @luismendoza-ec doesn't want to share anything ....

Let me understand you, Jairo. Throughout my development and testing, I tried to reach out to you, I wrote to you, left comments here, but got no response from you. On top of that, I shared a solution, but it seemed you weren’t interested at the time. Now it seems you’re tired of trying your way and want to use my solution, and you’re saying I don’t want to share?

Honestly, I’d rather keep my version private. None of you have shared anything concrete, just vague hints.

**Comment by jairoxyz** [comment]
@luismendoza-ec really? Maybe a misunderstanding? I shared my private git, which is a working solution, contacted you by email and send you my discord account. Didn't you receive that?

**Comment by WBRK-dev** [comment]
Is anyone interested in developing a public solution with me?
I think the first iteration should definitely be build with a headless browser since that is just quicker to implement.
After that if we think that it is possible to decrypt without a headless browser we can attempt that.

If anyone is interested then I can invite u to a repository to exchange discord handles and create a server if there are more than two?

**Comment by luismendoza-ec** [comment]
> Is anyone interested in developing a public solution with me? I think the first iteration should definitely be build with a headless browser since that is just quicker to implement. After that if we think that it is possible to decrypt without a headless browser we can attempt that.
> 
> If anyone is interested then I can invite u to a repository to exchange discord handles and create a server if there are more than two?

I am interested.

**Comment by WBRK-dev** [comment]
@jairoxyz, @luismendoza-ec 
I have invited you both.
In the issues page, you can find my Discord handle.

**Comment by justchokingaround** [comment]
can you invite me as well pls @WBRK-dev ? i'm not currently working on foss stuff but i'm interested in keeping up with this

**Comment by WBRK-dev** [comment]
@justchokingaround 
You have been invited.

**Comment by BominRahmani** [comment]
@WBRK-dev I'd love to keep up with this as well, not sure if i'll be able to work on it right now, but i'd love to see any further developments.

**Comment by Xross342** [comment]
Hello guys, I have a working rabbit stream fix BUT it only works on the browser with the no cors extension on, but it successfully decrypts rabbit stream without using a headless browser, i kinda don’t have time to work on it but I want to nicely ask. Can someone please implement the fixed into rabbit_wasm, you can dm me on discord for the code  My discord is Zetsman192

**Comment by Xross342** [comment]
> Hello guys, I have a working rabbit stream fix BUT it only works on the browser with the no cors extension on, but it successfully decrypts rabbit stream without using a headless browser, i kinda don’t have time to work on it but I want to nicely ask. Can someone please implement the fixed into rabbit_wasm, you can dm me on discord for the code My discord is Zetsman192

Sorry, wrong discord. the right one ix xross342

**Comment by kelgr** [comment]
@WBRK-dev could you please provide discord server, im interested in the project

**Comment by AndresDevvv** [comment]
I'd like to be added into this project, thank you!

**Comment by shashstormer** [comment]
I'D like to join the project too

**Comment by WBRK-dev** [comment]
Hello @BominRahmani @kelgr @AndresDevvv @shashstormer 

The group has kinda already been disbanded.

Sorry for the late reaction.

**Comment by ritesshg** [comment]
> Hey friends! It’s been a few interesting days trying to solve this, and JSDom and other techniques to represent things even close to what I need have made everything quite complicated. The validation and generation of the fingerprint is complex and depends on many factors, so even a minor change can prevent it from generating correctly.
> 
> The best solution I could implement (after temporarily handling Puppeteer and pools to intercept the HLS) is the following:
> 
> 1. A single Puppeteer instance that doesn’t demand much from the system serves as the perfect sandbox, allowing all validations and WebAssembly (WASM) operations to run smoothly.
> 2. Injection of modified code to control certain aspects, validations, and shape the data exactly as I need it.
> 3. The browser’s connection to a socket hub that allows me to control it on demand (not to be confused with a reload operation).
> 
> **What I’m practically doing is:**
> 
> * Loading the site just once, letting resources and validations take place, and preventing resources that might later block from being released.
> * Making this sandbox communicate via sockets to handle my requests.
> * From my script that I want to scrape, I send the media ID I need.
> * The sandbox (without any HTTP requests) generates the necessary fingerprint (which I’ve modified in certain parts to make unique).
> * The sandbox responds with the fingerprint and other parameters needed for the request.
> * From my script’s side, I make the request for the sources, and with the data obtained, apply the logic of their obfuscation to decrypt it.
> * On the script’s side, I sanitize the URL and get it ready for consumption.
> 
> **Requests:**
> 
> * The browser only makes one to load the sandbox (resources, WASM, etc.).
> * The script makes one to fetch the unique data of each embed and another to get the source (a JSON with the encrypted source). After that, I have the HLS.
> 
> I’ve tested it with some embeds, and it’s going well, and the best part is that it works in headless mode.
> 
> I’m leaving a few images and signing off (I need to sleep).
> 
> **P.D.:** I’ll improve a few things when I return with recharged energy. I know I can make it even better, but as it stands, it works very well.
> 
> ![image](https://private-user-images.githubusercontent.com/125885777/382042572-27e56c5c-748b-45be-953b-f73cff11bfef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyOTc4OTAsIm5iZiI6MTczNDI5NzU5MCwicGF0aCI6Ii8xMjU4ODU3NzcvMzgyMDQyNTcyLTI3ZTU2YzVjLTc0OGItNDViZS05NTNiLWY3M2NmZjExYmZlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQyMTE5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWRhNGRmODJlNjc3NjAxNzEzYWEwZjhmMjdlYzgwN2UyNGYzNjQ2MTkxNDQ4Y2QwZmY3MTA2ZTA1OTUyODBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vg93TAm1U2q-TWp83xz6gPyI4kM_7QTQeoX5cELhXNA) <img alt="image" width="1139" src="https://private-user-images.githubusercontent.com/125885777/382042646-59db5d45-3801-4060-8519-cacaf3bfaf80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyOTc4OTAsIm5iZiI6MTczNDI5NzU5MCwicGF0aCI6Ii8xMjU4ODU3NzcvMzgyMDQyNjQ2LTU5ZGI1ZDQ1LTM4MDEtNDA2MC04NTE5LWNhY2FmM2JmYWY4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQyMTE5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTE4MzA2MjI0NjEzYzJjMjYwNjQyZDY4ZmU3ZDQ4ZTQ2ZDU0NzFhMmFhOWFjYzAxOTM5MWQ1MzJlNGIyNmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WgFl8rvH9TMEZJTykcmO_6CP0nV_VR5eGYImLVkx5BY"> ![image](https://private-user-images.githubusercontent.com/125885777/382042998-303170de-d784-4b1b-8ab3-17248c0e4189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyOTc4OTAsIm5iZiI6MTczNDI5NzU5MCwicGF0aCI6Ii8xMjU4ODU3NzcvMzgyMDQyOTk4LTMwMzE3MGRlLWQ3ODQtNGIxYi04YWIzLTE3MjQ4YzBlNDE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQyMTE5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzI4N2JjNmQ0MzE1MzIzNzJkM2VmMWI1ODE3NzEwNDdlYWZhY2JjYmE0MDRhZmFlYTg3ODkxYzQzOGY2MzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u1700kKsGLjfL-6nx1bg_AbiyQ05sqbU2ArbU4IhI-s)

this seems like a really good idea for the first iteration

**Comment by drblgn** [comment]
hey yo, back from the dead. just gonna push a quick fix. lemme know if it works.
ps: didnt do much testing

**Comment by streamamos** [comment]
> hey yo, back from the dead. just gonna push a quick fix. lemme know if it works. ps: didnt do much testing

Hi, thanks for the fix, can you also update the api repo? I tried to "fixed" it on my own (basically just copy and pasted) but it only works for like the two first requests.

**Comment by drblgn** [comment]
> > hey yo, back from the dead. just gonna push a quick fix. lemme know if it works. ps: didnt do much testing
> 
> Hi, thanks for the fix, can you also update the api repo? I tried to "fixed" it on my own (basically just copy and pasted) but it only works for like the two first requests.

just pushed an update

**Comment by doiraduc** [comment]
Thank you so much for this long awaited fix. It would be nice to support megacloud too as these sites seem to be moving forward to this newer embed, (for example sflix(dot)to moved to sflix2(dot)to that changed the embed to megacloud), but it is still a pretty good solution to use these older sites too (the caveat is that they work so much slower).
I will close this issue and, in case the player is updated again and it won't work anymore, I will reopen it.
Again, thank you so much.
