### ISSUE TITLE
Error during decryption

### ISSUE THREAD

**Issue by itzzzme** [drblgn/rabbit_wasm#7]
Getting the error 

`TypeError: fake_window.navigate is not a function`

![Screenshot 2024-12-19 031316-mh](https://github.com/user-attachments/assets/5334e607-2d9a-453b-85bc-871fdea382a2)

This red marked line throwing the error. Can you tell what went wrong

**Comment by jairoxyz** [comment]
Works fine here. Share the complete code your are trying. Are you using an updated xrax?

**Comment by itzzzme** [comment]
> Works fine here. Share the complete code your are trying. Are you using an updated xrax?

The script is for Rabbitstream. But I am using it for megacloud.tv since the architecture of their website is exactly the same. 

https://github.com/itzzzme/anime-api/blob/main/src/parsers/decryptors/megacloud.decryptor.js

Here is the full code

**Comment by jairoxyz** [comment]
You need to change some urls to use it for megacloud: embed url is /embed-1/e-1/ and getsources url is embed-1/ajax/e-1/getSources. Plus referer has to be changed. 
OK I see you did that. Should work then. Works fine here for megacloud.tube. Try embed-1/e-1 instead of embed-2/e-1

https://megacloud.tube/embed-1/e-1/6vtb50LJz757?z=

<img width="562" alt="image" src="https://github.com/user-attachments/assets/122fdf00-76a2-4ea9-ad87-4e1f593ccc3f" />

**Comment by itzzzme** [comment]
> You need to change some urls to use it for megacloud: embed url is /embed-1/e-1/ and getsources url is embed-1/ajax/e-1/getSources. Plus referer has to be changed. 
> OK I see you did that. Should work then. Works fine here for megacloud.tube. Try embed-1/e-1 instead of embed-2/e-1
> 
> https://megacloud.tube/embed-1/e-1/6vtb50LJz757?z=
> 
> <img width="562" alt="image" src="https://github.com/user-attachments/assets/122fdf00-76a2-4ea9-ad87-4e1f593ccc3f" />
> 

But is it working for you with megacloud.tv as well?

**Comment by jairoxyz** [comment]
Yes I used .tv in example above. But I don't know about embed-2. Maybe they use different code and wasm?

**Comment by drblgn** [comment]
just pushed an update to add mega support, try it and let me know

**Comment by itzzzme** [comment]
@drblgn Yes it's working fine , just a small correction while extracting xrax from embed_url

![Screenshot 2024-12-19 114505-mh](https://github.com/user-attachments/assets/24e689a1-e28d-45f1-b073-e4a3d3d7415a)

Instead of doing this I will suggest do this

![image](https://github.com/user-attachments/assets/38f3d94a-5336-442a-b209-7da938014b4d)

while using the regx method I gave an embed_url

e.g: `https://megacloud.tv/embed-2/e-1/3gJEWARkF3q6?k=1`

the extracted xrax using regx was `JEWARkF3q6` but it should be `3gJEWARkF3q6` so I think the second method will be more viable. 

Thanks for the help btw!

**Comment by itzzzme** [comment]
@drblgn @jairoxyz  Hey there is one more problem with the code

`Scenario`:  I created a temp api integrating the code

`Issue`:  When you first send request to the server for a particular `embed_id` **_API_** gives the correct output but if you give different `embed_id`  the **_API_** don't give any output anymore


https://github.com/user-attachments/assets/cda60b21-ddc9-426c-8002-d6cb1efa4741

**Comment by jairoxyz** [comment]
Try using different embed ids with the decryptor alone without API and see if that works. The do some debugging to see what's happening.  I don't have any issues with it.

**Comment by itzzzme** [comment]
@Xross342 Yeah it worked. Thanks mate
